-- =====================================================================
--  OBSOLETE — THIS FILE IS **NOT** THE SOURCE OF TRUTH.
--
--  Kept only as a historical record of the pre-consolidation schema. Do not
--  introspect it, do not run it, and do not reason about the live shape from
--  it. The source of truth is prisma/schema.prisma, generated by
--  `prisma db pull` against the live database.
--
--  Verified divergence from live (see PLAN.md section 3 for the full evidence):
--    * 35 tables here, 35 live, but only 29 SHARED.
--    * Missing from this file, present live: attendance, expense_categories,
--      point_config, point_config_history, point_events, tenant_point_settings.
--    * Present here, absent live: dealers, distributors, institutions, levels,
--      user_audit_logs, user_login_logs. The first three were consolidated into
--      business_partners; this file predates that change.
--    * Column-level drift too, e.g. role_permissions.section's CHECK constraint
--      here allows 5 values while live data holds 23 distinct ones, and
--      users.level_id is declared NOT NULL against a column that does not exist.
--
--  Regenerate the real schema with:  npm run prisma:sync
-- =====================================================================

-- ============================================================
-- RGB SFA Admin — Full Schema Migration
-- Run in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- ============================================================

-- ----------------------------------------------------------------
-- DROP old tables (from previous SERIAL-PK schema) — safe to re-run
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS weekly_plan_audit_logs CASCADE;
DROP TABLE IF EXISTS weekly_plan_items CASCADE;
DROP TABLE IF EXISTS weekly_plans CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS levels CASCADE;
DROP TABLE IF EXISTS designations CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS product_subcategories CASCADE;
DROP TABLE IF EXISTS product_categories CASCADE;
DROP TABLE IF EXISTS dealers CASCADE;
DROP TABLE IF EXISTS distributors CASCADE;
DROP TABLE IF EXISTS villages CASCADE;
DROP TABLE IF EXISTS talukas CASCADE;
DROP TABLE IF EXISTS districts CASCADE;
DROP TABLE IF EXISTS states CASCADE;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------------------------------------------
-- Shared trigger: updated_at
-- ----------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ================================================================
-- A) LOCATION MASTERS
-- ================================================================

CREATE TABLE IF NOT EXISTS states (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id  UUID NOT NULL,
  name       TEXT NOT NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS states_tenant_name ON states(tenant_id, LOWER(name));
CREATE OR REPLACE TRIGGER states_updated_at BEFORE UPDATE ON states FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE states ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS districts (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id  UUID NOT NULL,
  state_id   UUID NOT NULL REFERENCES states(id) ON DELETE RESTRICT,
  name       TEXT NOT NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS districts_tenant_state_name ON districts(tenant_id, state_id, LOWER(name));
CREATE OR REPLACE TRIGGER districts_updated_at BEFORE UPDATE ON districts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE districts ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS talukas (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id   UUID NOT NULL,
  district_id UUID NOT NULL REFERENCES districts(id) ON DELETE RESTRICT,
  name        TEXT NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS talukas_tenant_district_name ON talukas(tenant_id, district_id, LOWER(name));
CREATE OR REPLACE TRIGGER talukas_updated_at BEFORE UPDATE ON talukas FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE talukas ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS villages (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id  UUID NOT NULL,
  taluka_id  UUID NOT NULL REFERENCES talukas(id) ON DELETE RESTRICT,
  name       TEXT NOT NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS villages_tenant_taluka_name ON villages(tenant_id, taluka_id, LOWER(name));
CREATE OR REPLACE TRIGGER villages_updated_at BEFORE UPDATE ON villages FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE villages ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- B) BUSINESS MASTERS
-- ================================================================

CREATE TABLE IF NOT EXISTS distributors (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id   UUID NOT NULL,
  name        TEXT NOT NULL,
  phone       TEXT,
  email       TEXT,
  address     TEXT,
  state_id    UUID REFERENCES states(id)    ON DELETE SET NULL,
  district_id UUID REFERENCES districts(id) ON DELETE SET NULL,
  taluka_id   UUID REFERENCES talukas(id)   ON DELETE SET NULL,
  village_id  UUID REFERENCES villages(id)  ON DELETE SET NULL,
  latitude    NUMERIC(10,7),
  longitude   NUMERIC(10,7),
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT distributors_lat_check CHECK (latitude  IS NULL OR (latitude  >= -90  AND latitude  <= 90)),
  CONSTRAINT distributors_lng_check CHECK (longitude IS NULL OR (longitude >= -180 AND longitude <= 180))
);
CREATE OR REPLACE TRIGGER distributors_updated_at BEFORE UPDATE ON distributors FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE distributors ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS dealers (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id       UUID NOT NULL,
  distributor_id  UUID REFERENCES distributors(id) ON DELETE SET NULL,
  name            TEXT NOT NULL,
  state_id        UUID NOT NULL REFERENCES states(id),
  district_id     UUID NOT NULL REFERENCES districts(id),
  taluka_id       UUID NOT NULL REFERENCES talukas(id),
  village_id      UUID REFERENCES villages(id),
  latitude        NUMERIC(10,7),
  longitude       NUMERIC(10,7),
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT dealers_lat_check CHECK (latitude IS NULL OR (latitude >= -90 AND latitude <= 90)),
  CONSTRAINT dealers_lng_check CHECK (longitude IS NULL OR (longitude >= -180 AND longitude <= 180))
);
CREATE OR REPLACE TRIGGER dealers_updated_at BEFORE UPDATE ON dealers FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE dealers ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- C) PRODUCT MASTERS
-- ================================================================

CREATE TABLE IF NOT EXISTS product_categories (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id  UUID NOT NULL,
  name       TEXT NOT NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS product_categories_tenant_name ON product_categories(tenant_id, LOWER(name));
CREATE OR REPLACE TRIGGER product_categories_updated_at BEFORE UPDATE ON product_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS product_subcategories (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id   UUID NOT NULL,
  category_id UUID NOT NULL REFERENCES product_categories(id) ON DELETE RESTRICT,
  name        TEXT NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS product_subcategories_tenant_cat_name ON product_subcategories(tenant_id, category_id, LOWER(name));
CREATE OR REPLACE TRIGGER product_subcategories_updated_at BEFORE UPDATE ON product_subcategories FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE product_subcategories ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS products (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id      UUID NOT NULL,
  name           TEXT NOT NULL,
  category_id    UUID NOT NULL REFERENCES product_categories(id),
  subcategory_id UUID NOT NULL REFERENCES product_subcategories(id),
  price          NUMERIC(12,2) NOT NULL,
  sku            TEXT,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE TRIGGER products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- D) ORGANIZATION MASTERS
-- ================================================================

CREATE TABLE IF NOT EXISTS departments (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id  UUID NOT NULL,
  name       TEXT NOT NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS departments_tenant_name ON departments(tenant_id, LOWER(name));
CREATE OR REPLACE TRIGGER departments_updated_at BEFORE UPDATE ON departments FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS designations (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id     UUID NOT NULL,
  department_id UUID NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
  name          TEXT NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE TRIGGER designations_updated_at BEFORE UPDATE ON designations FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE designations ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS levels (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id  UUID NOT NULL,
  level_no   INT NOT NULL,
  name       TEXT NOT NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS levels_tenant_level_no ON levels(tenant_id, level_no);
CREATE OR REPLACE TRIGGER levels_updated_at BEFORE UPDATE ON levels FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE levels ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- E) USERS + HIERARCHY
-- ================================================================

CREATE TABLE IF NOT EXISTS users (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id       UUID NOT NULL,
  name            TEXT NOT NULL,
  email           TEXT NOT NULL,
  contact         TEXT NOT NULL,
  password        TEXT NOT NULL DEFAULT '',
  department_id   UUID REFERENCES departments(id),
  designation_id  UUID REFERENCES designations(id),
  level_id        UUID NOT NULL REFERENCES levels(id),
  profile         TEXT NOT NULL DEFAULT 'Standard' CHECK (profile IN ('Administrator', 'Standard')),
  manager_user_id UUID REFERENCES users(id),
  status          TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS users_tenant_contact ON users(tenant_id, contact);
CREATE OR REPLACE TRIGGER users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- F) DAILY ACTIVITY VISITS
-- ================================================================

CREATE TABLE IF NOT EXISTS daily_visits (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id     UUID NOT NULL,
  user_id       UUID NOT NULL REFERENCES users(id),
  visit_date    DATE NOT NULL,
  visit_type    TEXT NOT NULL CHECK (visit_type IN ('Dealer', 'Distributor')),
  entity_id     UUID,
  entity_name   TEXT NOT NULL,
  is_new_entity BOOLEAN NOT NULL DEFAULT FALSE,
  start_time    TIMESTAMPTZ,
  end_time      TIMESTAMPTZ,
  duration_secs INT,
  latitude      NUMERIC(10,7),
  longitude     NUMERIC(10,7),
  address       TEXT,
  status        TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Active', 'Completed')),
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE TRIGGER daily_visits_updated_at BEFORE UPDATE ON daily_visits FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE daily_visits ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- H) TERRITORY MAPPING
-- ================================================================

CREATE TABLE IF NOT EXISTS user_territory_mappings (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id   UUID NOT NULL,
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  state_ids   UUID[] NOT NULL DEFAULT '{}',
  district_ids UUID[] NOT NULL DEFAULT '{}',
  taluka_ids  UUID[] NOT NULL DEFAULT '{}',
  village_ids UUID[] NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tenant_id, user_id)
);
CREATE OR REPLACE TRIGGER user_territory_mappings_updated_at BEFORE UPDATE ON user_territory_mappings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE user_territory_mappings ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- G) WEEKLY PLAN
-- ================================================================

CREATE TABLE IF NOT EXISTS weekly_plans (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id             UUID NOT NULL,
  user_id               UUID NOT NULL REFERENCES users(id),
  week_start_date       DATE NOT NULL,
  week_end_date         DATE NOT NULL,
  status                TEXT NOT NULL DEFAULT 'Draft'
    CHECK (status IN ('Draft','Submitted','Approved','Rejected','On Hold','Edited by Manager','Resubmitted')),
  submitted_at          TIMESTAMPTZ,
  last_status_changed_at TIMESTAMPTZ DEFAULT NOW(),
  current_manager_id    UUID REFERENCES users(id),
  manager_comment       TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tenant_id, user_id, week_start_date)
);
CREATE OR REPLACE TRIGGER weekly_plans_updated_at BEFORE UPDATE ON weekly_plans FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE weekly_plans ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS weekly_plan_items (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id             UUID NOT NULL,
  weekly_plan_id        UUID NOT NULL REFERENCES weekly_plans(id) ON DELETE CASCADE,
  plan_date             DATE NOT NULL,
  from_place            TEXT,
  to_place              TEXT,
  new_dealers_goal      INT DEFAULT 0,
  existing_dealers_goal INT DEFAULT 0,
  mode_of_travel        TEXT CHECK (mode_of_travel IN ('Bike','Bus','Car','Train')),
  notes                 TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE TRIGGER weekly_plan_items_updated_at BEFORE UPDATE ON weekly_plan_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE weekly_plan_items ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- G) IMMUTABLE AUDIT LOG
-- ================================================================

CREATE TABLE IF NOT EXISTS weekly_plan_audit_logs (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id        UUID NOT NULL,
  weekly_plan_id   UUID NOT NULL REFERENCES weekly_plans(id),
  actor_user_id    UUID REFERENCES users(id),
  actor_role       TEXT NOT NULL,
  action_type      TEXT NOT NULL,
  timestamp        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  previous_status  TEXT,
  new_status       TEXT,
  comment          TEXT,
  edited_fields    JSONB,
  ip_address       TEXT,
  user_agent       TEXT
);
-- Append-only: no trigger, no UPDATE allowed via RLS
ALTER TABLE weekly_plan_audit_logs ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- I) EXPENSES
-- ================================================================

CREATE TABLE IF NOT EXISTS expenses (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id    UUID NOT NULL,
  user_id      UUID NOT NULL REFERENCES users(id),
  expense_date DATE NOT NULL,
  category     TEXT NOT NULL,
  amount       NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE TRIGGER expenses_updated_at BEFORE UPDATE ON expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- J) ORDERS (linked to a daily_visit / meeting)
-- ================================================================

CREATE TABLE IF NOT EXISTS orders (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id    UUID NOT NULL,
  user_id      UUID NOT NULL REFERENCES users(id),
  visit_id     UUID NOT NULL REFERENCES daily_visits(id) ON DELETE CASCADE,
  order_date   DATE NOT NULL,
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(visit_id)
);
CREATE OR REPLACE TRIGGER orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- K) ORDER ITEMS
-- ================================================================

CREATE TABLE IF NOT EXISTS order_items (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id    UUID NOT NULL,
  order_id     UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id   UUID REFERENCES products(id),
  product_name TEXT NOT NULL,
  qty          INT NOT NULL DEFAULT 1 CHECK (qty > 0),
  rate         NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (rate >= 0),
  amount       NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- L) CONTEXTUAL REMARKS (polymorphic)
-- ================================================================

CREATE TABLE IF NOT EXISTS contextual_remarks (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id        UUID NOT NULL,
  context_type     TEXT NOT NULL CHECK (context_type IN ('meeting','expense','weekly_plan_day')),
  context_id       UUID NOT NULL,
  parent_remark_id UUID REFERENCES contextual_remarks(id) ON DELETE CASCADE,
  author_user_id   UUID NOT NULL REFERENCES users(id),
  body             TEXT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS remarks_context ON contextual_remarks(tenant_id, context_type, context_id);
CREATE OR REPLACE TRIGGER contextual_remarks_updated_at BEFORE UPDATE ON contextual_remarks FOR EACH ROW EXECUTE FUNCTION update_updated_at();
ALTER TABLE contextual_remarks ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- M) REMARK READS (per-user read tracking)
-- ================================================================

CREATE TABLE IF NOT EXISTS remark_reads (
  id        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  remark_id UUID NOT NULL REFERENCES contextual_remarks(id) ON DELETE CASCADE,
  user_id   UUID NOT NULL REFERENCES users(id),
  read_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(remark_id, user_id)
);
ALTER TABLE remark_reads ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- N) NOTIFICATIONS
-- ================================================================

CREATE TABLE IF NOT EXISTS notifications (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id     UUID NOT NULL,
  recipient_id  UUID NOT NULL REFERENCES users(id),
  actor_id      UUID REFERENCES users(id),
  section       TEXT NOT NULL CHECK (section IN ('weekly_plan','meeting','expense')),
  context_type  TEXT NOT NULL,
  context_id    UUID NOT NULL,
  remark_id     UUID REFERENCES contextual_remarks(id) ON DELETE SET NULL,
  redirect_path TEXT NOT NULL,
  message       TEXT NOT NULL,
  is_read       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS notifications_recipient ON notifications(tenant_id, recipient_id, is_read);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- O) USER VISIBILITY (configurable cross-team access)
-- ================================================================
-- Run this block ONCE after the initial schema is deployed.
-- It is safe to re-run (IF NOT EXISTS + ON CONFLICT DO NOTHING).

CREATE TABLE IF NOT EXISTS user_visibility (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id       UUID NOT NULL,
  viewer_user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(viewer_user_id, target_user_id)
);
CREATE INDEX IF NOT EXISTS uv_viewer ON user_visibility(tenant_id, viewer_user_id);
ALTER TABLE user_visibility ENABLE ROW LEVEL SECURITY;

-- Seed from existing hierarchy (zero-disruption migration)
-- Existing managers retain their current subordinate visibility.
INSERT INTO user_visibility (tenant_id, viewer_user_id, target_user_id)
SELECT tenant_id, manager_user_id, id
FROM users
WHERE manager_user_id IS NOT NULL
ON CONFLICT DO NOTHING;

-- ================================================================
-- RLS POLICIES (Service Role bypasses RLS — anon gets nothing)
-- ================================================================
-- NOTE: All server-side operations use SUPABASE_SERVICE_ROLE_KEY which
-- bypasses RLS. Anon/authenticated client access is denied by default.
-- To enable fine-grained RLS later, add policies per table.
-- For now: no policies = default deny for anon key.
-- ================================================================

-- ================================================================
-- role_permissions — configurable per-section permissions for Standard role
-- ================================================================
CREATE TABLE IF NOT EXISTS role_permissions (
  id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   UUID    NOT NULL,
  profile     TEXT    NOT NULL CHECK (profile IN ('Standard')),
  section     TEXT    NOT NULL CHECK (section IN ('locations','business','products','organization','users')),
  can_view    BOOLEAN NOT NULL DEFAULT false,
  can_edit    BOOLEAN NOT NULL DEFAULT false,
  can_delete  BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (tenant_id, profile, section)
);
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- Expenses — photo attachment
-- ================================================================
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS photo_url TEXT;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('expense-photos', 'expense-photos', true, 5242880, ARRAY['image/jpeg','image/jpg','image/png'])
ON CONFLICT (id) DO NOTHING;

-- ================================================================
-- Password Reset Tokens
-- ================================================================
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_reset_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_reset_expires TIMESTAMPTZ;

-- ================================================================
-- Institutions / Consumers
-- ================================================================
CREATE TABLE IF NOT EXISTS institutions (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    UUID        NOT NULL,
  name         TEXT        NOT NULL,
  phone        TEXT,
  address      TEXT,
  description  TEXT,
  state_id     UUID        REFERENCES states(id),
  district_id  UUID        REFERENCES districts(id),
  taluka_id    UUID        REFERENCES talukas(id),
  village_id   UUID        REFERENCES villages(id),
  latitude     NUMERIC(10,7),
  longitude    NUMERIC(10,7),
  is_active    BOOLEAN     NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE institutions ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER set_institutions_updated_at
  BEFORE UPDATE ON institutions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ================================================================
-- Business Partners: unified table replacing dealers + distributors + institutions
-- ================================================================
CREATE TABLE IF NOT EXISTS business_partners (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID        NOT NULL,
  type            TEXT        NOT NULL CHECK (type IN ('Dealer', 'Distributor', 'Institution / Consumer')),
  name            TEXT        NOT NULL,
  distributor_id  UUID        REFERENCES business_partners(id) ON DELETE SET NULL,
  phone           TEXT,
  address         TEXT,
  description     TEXT,
  state_id        UUID        REFERENCES states(id),
  district_id     UUID        REFERENCES districts(id),
  taluka_id       UUID        REFERENCES talukas(id),
  village_id      UUID        REFERENCES villages(id),
  latitude        NUMERIC(10,7),
  longitude       NUMERIC(10,7),
  is_active       BOOLEAN     NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE business_partners ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER set_business_partners_updated_at
  BEFORE UPDATE ON business_partners
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Data migration: distributors first (preserving UUIDs so dealer FK refs resolve)
INSERT INTO business_partners (id, tenant_id, type, name, phone, address, description, state_id, district_id, taluka_id, village_id, latitude, longitude, is_active, created_at, updated_at)
SELECT id, tenant_id, 'Distributor', name, phone, address, description, state_id, district_id, taluka_id, village_id, latitude, longitude, is_active, created_at, updated_at
FROM distributors ON CONFLICT (id) DO NOTHING;

INSERT INTO business_partners (id, tenant_id, type, name, phone, address, description, state_id, district_id, taluka_id, village_id, latitude, longitude, is_active, created_at, updated_at)
SELECT id, tenant_id, 'Institution / Consumer', name, phone, address, description, state_id, district_id, taluka_id, village_id, latitude, longitude, is_active, created_at, updated_at
FROM institutions ON CONFLICT (id) DO NOTHING;

INSERT INTO business_partners (id, tenant_id, type, name, phone, address, description, state_id, district_id, taluka_id, village_id, latitude, longitude, distributor_id, is_active, created_at, updated_at)
SELECT id, tenant_id, 'Dealer', name, phone, address, description, state_id, district_id, taluka_id, village_id, latitude, longitude, distributor_id, is_active, created_at, updated_at
FROM dealers ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------
-- tenants table (Super Admin panel — multi-tenant management)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tenants (
  id              UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  name            TEXT    NOT NULL,
  email           TEXT,
  phone           TEXT,
  address         TEXT,
  gstin           TEXT,
  license_count   INT     NOT NULL DEFAULT 10,
  payment_status  TEXT    NOT NULL DEFAULT 'Active'
    CHECK (payment_status IN ('Active', 'Overdue', 'Suspended')),
  payment_due_date DATE,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO tenants (id, name, license_count, payment_status)
VALUES ('00000000-0000-0000-0000-000000000001', 'Nuetech Solar Systems', 100, 'Active')
ON CONFLICT (id) DO NOTHING;

-- ================================================================
-- Allow Institution / Consumer as a visit type in daily_visits
-- ================================================================
ALTER TABLE daily_visits
  DROP CONSTRAINT IF EXISTS daily_visits_visit_type_check;
ALTER TABLE daily_visits
  ADD CONSTRAINT daily_visits_visit_type_check
  CHECK (visit_type IN ('Dealer', 'Distributor', 'Institution / Consumer'));

-- ================================================================
-- Lead Lifecycle System
-- ================================================================
CREATE TABLE IF NOT EXISTS lead_types (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL,
  name TEXT NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS lead_stages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL,
  name TEXT NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  is_fixed BOOLEAN NOT NULL DEFAULT false, is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS lead_temperatures (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL,
  name TEXT NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE business_partners DROP CONSTRAINT IF EXISTS business_partners_type_check;
ALTER TABLE business_partners ADD COLUMN IF NOT EXISTS stage TEXT NOT NULL DEFAULT 'Existing',
  ADD COLUMN IF NOT EXISTS temperature TEXT, ADD COLUMN IF NOT EXISTS next_follow_up_date DATE;
UPDATE business_partners SET type = 'Institution'  WHERE type = 'Institution / Consumer' AND sub_type = 'Institution';
UPDATE business_partners SET type = 'End Consumer' WHERE type = 'Institution / Consumer' AND sub_type = 'Consumer';
UPDATE business_partners SET type = 'Institution'  WHERE type = 'Institution / Consumer';
ALTER TABLE daily_visits DROP CONSTRAINT IF EXISTS daily_visits_visit_type_check;
INSERT INTO lead_types (tenant_id, name, sort_order) VALUES
  ('00000000-0000-0000-0000-000000000001','Dealer',1),('00000000-0000-0000-0000-000000000001','Distributor',2),
  ('00000000-0000-0000-0000-000000000001','Institution',3),('00000000-0000-0000-0000-000000000001','End Consumer',4)
ON CONFLICT DO NOTHING;
INSERT INTO lead_stages (tenant_id, name, sort_order, is_fixed) VALUES
  ('00000000-0000-0000-0000-000000000001','Prospect',1,true),('00000000-0000-0000-0000-000000000001','Contacted',2,false),
  ('00000000-0000-0000-0000-000000000001','Interested',3,false),('00000000-0000-0000-0000-000000000001','Qualified',4,false),
  ('00000000-0000-0000-0000-000000000001','Proposal',5,false),('00000000-0000-0000-0000-000000000001','Negotiation',6,false),
  ('00000000-0000-0000-0000-000000000001','Existing',999,true)
ON CONFLICT DO NOTHING;
INSERT INTO lead_temperatures (tenant_id, name, sort_order) VALUES
  ('00000000-0000-0000-0000-000000000001','Cold',1),('00000000-0000-0000-0000-000000000001','Warm',2),
  ('00000000-0000-0000-0000-000000000001','Hot',3)
ON CONFLICT DO NOTHING;

-- ================================================================
-- access_control_redesign
-- Custom roles, can_create permission, transitive visibility cascade
-- ================================================================

CREATE TABLE IF NOT EXISTS roles (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id  UUID NOT NULL,
  name       TEXT NOT NULL,
  is_system  BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tenant_id, name)
);
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;

INSERT INTO roles (tenant_id, name, is_system)
SELECT DISTINCT tenant_id, 'Administrator', true FROM users ON CONFLICT (tenant_id, name) DO NOTHING;
INSERT INTO roles (tenant_id, name, is_system)
SELECT DISTINCT tenant_id, 'Standard', true FROM users ON CONFLICT (tenant_id, name) DO NOTHING;

ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id UUID REFERENCES roles(id);
UPDATE users u SET role_id = r.id FROM roles r WHERE r.tenant_id = u.tenant_id AND r.name = u.profile AND u.role_id IS NULL;

ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS can_create BOOLEAN NOT NULL DEFAULT false;
UPDATE role_permissions SET can_create = can_edit WHERE can_create = false AND can_edit = true;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_profile_check;
ALTER TABLE role_permissions DROP CONSTRAINT IF EXISTS role_permissions_profile_check;

-- ================================================================
-- role_permissions_data_scope
-- data_scope column: 'own' | 'team' | 'all'
-- ================================================================
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS data_scope TEXT NOT NULL DEFAULT 'team';
UPDATE role_permissions SET data_scope = 'own' WHERE profile = 'Standard';
UPDATE role_permissions SET data_scope = 'all' WHERE profile = 'Administrator';

-- ================================================================
-- user_usage_intelligence
-- Login event tracking for User Usage Intelligence system
-- ================================================================
CREATE TABLE IF NOT EXISTS user_login_logs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id       UUID NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  logged_in_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address    TEXT,
  user_agent    TEXT
);

-- Fast per-user timeline queries
CREATE INDEX IF NOT EXISTS idx_ull_tenant_user_time
  ON user_login_logs (tenant_id, user_id, logged_in_at DESC);

-- Fast tenant-wide aggregation queries
CREATE INDEX IF NOT EXISTS idx_ull_tenant_time
  ON user_login_logs (tenant_id, logged_in_at DESC);

ALTER TABLE user_login_logs ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- user_audit_logs
-- Immutable log of user account lifecycle events (read-only by design)
-- ================================================================
CREATE TABLE IF NOT EXISTS user_audit_logs (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             UUID        NOT NULL,
  target_user_id        UUID        NOT NULL,
  target_user_name      TEXT        NOT NULL,
  action                TEXT        NOT NULL,  -- created | deactivated | reactivated | role_changed | name_changed
  performed_by_user_id  UUID,
  performed_by_name     TEXT        NOT NULL DEFAULT '',
  metadata              JSONB       NOT NULL DEFAULT '{}',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ual_tenant_time ON user_audit_logs (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ual_target_user ON user_audit_logs (tenant_id, target_user_id, created_at DESC);
ALTER TABLE user_audit_logs ENABLE ROW LEVEL SECURITY;
